name: "Active Directory authentication Add-on"
version: "1.0.1"
slug: "ldapauth"
description: "Active Directory authentication add-on for HAOS"
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
schema:
  ldap_server: str
  bind_user: str
  bind_password: str
  user_base_dn: str
  groups_base_dn: str
  user_group: str
  admin_group: str
ports:
  "8000/tcp": 8000
webui: "http://[HOST]:[PORT:8000]"