name: "Active Directory authentication Add-on"
version: "1.2.8"
slug: "ldapauth"
description: "Active Directory authentication add-on for HAOS"
url: https://github.com/janlon6260/home-assistant-active-directory-auth
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
log:
  max_size: 1m
  max_files: 1
map:
  - ssl:ro
  - share:rw
schema:
  ldap_server: str
  bind_user: str
  bind_password: password
  user_base_dn: str
  groups_base_dn: str
  user_group: str
  admin_group: str
  enable_ldaps: "bool?"
  ldaps_verify: "bool?"
  ldaps_ca_pem: "str?"
  debug_logging: "bool?"
ports:
  "8000/tcp": 8000
webui: "http://[HOST]:[PORT:8000]"